Repository GHOST-Science-Club/statutscan-app, pull requests merged in 2025-05, with the labels that each got.

#29 Monitoring token usage
  backend/chat/agent/agent.py
  backend/chat/agent/chat_history.py
  backend/chat/agent/generate_chat_title.py
  backend/chat/agent/generate_id.py
  backend/chat/agent/token_usage_manager.py
  backend/chat/agent/tools.py
  backend/chat/consumers.py
  backend/chat/views.py
  backend/requirements.txt
  backend/users/admin.py
  backend/users/migrations/0001_initial.py
  backend/users/models.py
Labels: new feature

#32 Redirection request
  backend/Dockerfile
  backend/Dockerfile.dev
  backend/Makefile
  backend/chat/agent/chat_history.py
  backend/chat/agent/generate_chat_title.py
  backend/chat/consumers.py
  backend/chat/middleware.py
  backend/chat/routing.py
  backend/chat/views.py
  backend/docker-compose.yml
  backend/entrypoint.sh
  backend/statutscan_project/asgi.py
Labels: bug

#35 fix: async websocket connection fix
  backend/chat/agent/agent.py
  backend/chat/agent/token_usage_manager.py
  backend/chat/consumers.py
  backend/chat/middleware.py
Labels: bug

#24 Prompt injection
  backend/chat/agent/agent.py
  backend/chat/agent/generate_chat_title.py
  backend/chat/agent/prompt_injection.py
Labels: new feature

#40 feat: run frontend and backend together
  Makefile
  README.md
  docker-compose.dev.yml
  frontend/Dockerfile.dev
Labels: new feature

#42 fix: makefile corrected env-file
  Makefile
Labels: code refactorization

#45 fix: fixed windows issue - auto changes applying to docker (multiplatform)
  .env.unix
  .env.windows
  docker-compose.dev.yml
  frontend/next.config.ts
Labels: code refactorization
